### PR TITLE
Feature/UI

### LINKED ISSUE #141: Implement GUI initial structure
1. Provide basic structure of the project. 
2. Use structure provided in demo UI wherever possible. 
3. Use same frameworks as in demo UI but with TypeScript on top

### PR DESCRIPTION
**Pull request by swaroopar**
Fix #141

### CODE REVIEW

**Comment by jbonofre** [comment]
Theorically, Xpanse/OSC should not provide any UI (or maybe the goals have changed).

**Comment by iskey** [comment]
> Theorically, Xpanse/OSC should not provide any UI (or maybe the goals have changed).



> Theorically, Xpanse/OSC should not provide any UI (or maybe the goals have changed).

yes, I agree
the UI here should be a simple demo to show what xpasne are and what they can be used for.

**Review by Alice1319 — APPROVED** [review]
looks good.

**Review by Alice1319 — APPROVED** [review]

**Review by iskey — APPROVED** [review]
looks good.

**Pull request merged**
